[package]
name = "intern_copilot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
serde_json = "1.0"
colored = "2.0"
owo-colors = "4.2.0"
reqwest = { version = "0.11.27", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.45", features = ["full", "macros", "rt-multi-thread"] }
thiserror = "2.0.12"
anyhow = "1.0"
once_cell = "1.21.3"
ollama-rs = "0.3.1"
axum = "0.8.4"
serde_derive = "1.0.219"
actix-web = { version = "4", features = ["macros"] }
futures-util = "0.3"
log = "0.4"
env_logger = "0.11"
